import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const myFont = localFont({
  src: [
    {
      path: "../public/assets/fonts/circular-std-medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/assets/fonts/circular-std-bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/assets/fonts/circular-std-black.ttf",
      weight: "900",
      style: "normal",
    },
    {
      path: "../public/assets/fonts/circular-std-medium-italic.ttf",
      weight: "500",
      style: "italic",
    },
    {
      path: "../public/assets/fonts/circular-std-bold-italic.ttf",
      weight: "700",
      style: "italic",
    },
    {
      path: "../public/assets/fonts/circular-std-black-italic.ttf",
      weight: "900",
      style: "italic",
    },
  ],
  variable: "--font-circular-std",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${myFont.variable} font-sans`}>
      <body>{children}</body>
    </html>
  );
}
